name: Chiu Riu Projekts
favicon: null
layout_spectrum: 0.22412732243537903
typography_spectrum: 0.9335536656435579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9316228651441634
  lightness: 0.1870670299977064
  saturation: 0.9029477511066943
  rhythmicContrast: 0.0387949482537806
purpose: []
